package br.org.cenmc.model;

public enum Tipo_Atividade {
	REUNIAO_PUBLICA,
	PASSE,
	ATENDIMENTO_FRATERNO,
	EVANGELIZAÇÃO_INFANTIL,
	REUNIÕES_DE_TRATAMENTO,
	REUNIÃO_DE_DISCIPLINA_MEDIÚNICA,
	JUVENTUDE,
	CEIDE,
	ESDE,
	TEMAS_DA_MEDIUNIDADE_1,
	TEMAS_DA_MEDIUNIDADE_2
}
